name: Map Diff

on:
  pull_request:
    paths:
    - '**.map'

jobs:
  comment-map-diff:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: actions/setup-node@v3.0.0
      with:
        node-version: '16'
    - name: Package install
      run: |
        cd ./utils/wesnoth-map-diff
        npm install
    - name: Package build
      run: |
        cd ./utils/wesnoth-map-diff
        npm run build:prod
    - name: Get maps diff
      id: get-maps-diff
      run: |
        cd ./utils/wesnoth-map-diff

        ## Get Maps
        git fetch --depth=1 origin ${{ github.event.pull_request.base.sha }}

        MAP_PATHS=$(git diff --name-only HEAD ${{ github.event.pull_request.base.sha }} | grep ".map$")

        for map_path in $MAP_PATHS
        do
          map_filename=$(echo "$map_path" | perl -pe 's/.*\///')
          git show ${{ github.event.pull_request.base.sha }}:$map_path > $map_filename
        done

        ## Run map diff
        diff_images=""

        for map_path in $MAP_PATHS
        do
          map_filename=$(echo "$map_path" | perl -pe 's/.*\///')
          output_filename=$(echo "$map_filename" | perl -pe 's/map$/png/')

          node ./build/index.js "./$map_filename" "../../$map_path" "./$output_filename"

          diff_images="$diff_images $output_filename"
        done

        ## Compress images
        sudo apt-get install -y pngquant

        for diff_image in $diff_images
        do
          pngquant "$diff_image" -o "$diff_image" --force
        done

        ## Write comment body
        comment_body=""

        for diff_image in $diff_images
        do
          image_link=$(curl -X POST "https://api.imgur.com/3/upload" \
            -F "image=@\"$diff_image\"" | jq ".data.link" -r)
          comment_body="$comment_body![]($image_link)<br/>"
        done

        echo "::set-output name=COMMENT_BODY::$comment_body"
    - name: Add comment
      uses: peter-evans/create-or-update-comment@v1.4.5
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ${{ steps.get-maps-diff.outputs.COMMENT_BODY }}
